######  Attributes Supported by Integration Apps #######
# id: Internal Id for the integrations, used by the hooks
# logo: place the image in /public/dashboard/images/integrations and reference here
# i18n_key: the key under which translations for the integration is placed in en.yml
# action: if integration requires external redirect url
# hook_type: ( account / inbox )
# feature_flag: (string) feature flag to enable/disable the integration
# allow_multiple_hooks: whether multiple hooks can be created for the integration
# settings_json_schema: the json schema used to validate the settings hash (https://json-schema.org/)
# settings_form_schema: the formulate schema used in frontend to render settings form (https://vueformulate.com/)
########################################################
webhooks:
  id: webhook
  logo: webhooks.png
  i18n_key: webhooks
  action: /webhook
  hook_type: account
  allow_multiple_hooks: true
dashboard_apps:
  id: dashboard_apps
  logo: dashboard_apps.png
  i18n_key: dashboard_apps
  hook_type: account
  allow_multiple_hooks: true
openai:
  id: openai
  logo: openai.png
  i18n_key: openai
  action: /openai
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'label_suggestion': { 'type': 'boolean' },
        },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
      {
        'label': 'Show label suggestions',
        'type': 'checkbox',
        'name': 'label_suggestion',
        'validation': '',
      },
    ]
  visible_properties: ['api_key', 'label_suggestion']
linear:
  id: linear
  logo: linear.png
  i18n_key: linear
  action: https://linear.app/oauth/authorize
  hook_type: account
  allow_multiple_hooks: false
slack:
  id: slack
  logo: slack.png
  i18n_key: slack
  action: https://slack.com/oauth/v2/authorize?scope=commands,chat:write,channels:read,channels:manage,channels:join,groups:read,groups:write,im:write,mpim:write,users:read,users:read.email,chat:write.customize,channels:history,groups:history,mpim:history,im:history,files:read,files:write
  hook_type: account
  allow_multiple_hooks: false
dialogflow:
  id: dialogflow
  logo: dialogflow.png
  i18n_key: dialogflow
  action: /dialogflow
  hook_type: inbox
  allow_multiple_hooks: true
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
          'language_code': { 'type': 'string' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Dialogflow Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Dialogflow Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
      {
        'label': 'Dialogflow Language Code',
        'type': 'select',
        'name': 'language_code',
        'options': [
          { 'label': 'Bengali (bn)', 'value': 'bn' },
          { 'label': 'Bengali - Bangladesh (bn-BD)', 'value': 'bn-BD' },
          { 'label': 'Bengali - India (bn-IN)', 'value': 'bn-IN' },
          { 'label': 'Chinese - Cantonese (zh-HK)', 'value': 'zh-HK' },
          { 'label': 'Chinese - Simplified (zh-CN)', 'value': 'zh-CN' },
          { 'label': 'Chinese - Traditional (zh-TW)', 'value': 'zh-TW' },
          { 'label': 'Danish (da)', 'value': 'da' },
          { 'label': 'Dutch (nl)', 'value': 'nl' },
          { 'label': 'English (en)', 'value': 'en' },
          { 'label': 'English - Australia (en-AU)', 'value': 'en-AU' },
          { 'label': 'English - Canada (en-CA)', 'value': 'en-CA' },
          { 'label': 'English - Great Britain (en-GB)', 'value': 'en-GB' },
          { 'label': 'English - India (en-IN)', 'value': 'en-IN' },
          { 'label': 'English - US (en-US)', 'value': 'en-US' },
          { 'label': 'Filipino (fil)', 'value': 'fil' },
          { 'label': 'Filipino - The Philippines (fil-PH)', 'value': 'fil-PH' },
          { 'label': 'Finnish (fi)', 'value': 'fi' },
          { 'label': 'French (fr)', 'value': 'fr' },
          { 'label': 'French - Canada (fr-CA)', 'value': 'fr-CA' },
          { 'label': 'French - France (fr-FR)', 'value': 'fr-FR' },
          { 'label': 'German (de)', 'value': 'de' },
          { 'label': 'Hindi (hi)', 'value': 'hi' },
          { 'label': 'Indonesian (id)', 'value': 'id' },
          { 'label': 'Italian (it)', 'value': 'it' },
          { 'label': 'Japanese (ja)', 'value': 'ja' },
          { 'label': 'Korean (ko)', 'value': 'ko' },
          { 'label': 'Malay (ms)', 'value': 'ms' },
          { 'label': 'Malay - Malaysia (ms-MY)', 'value': 'ms-MY' },
          { 'label': 'Marathi (mr)', 'value': 'mr' },
          { 'label': 'Marathi - India (mr-IN)', 'value': 'mr-IN' },
          { 'label': 'Norwegian (no)', 'value': 'no' },
          { 'label': 'Polish (pl)', 'value': 'pl' },
          { 'label': 'Portuguese - Brazil (pt-BR)', 'value': 'pt-BR' },
          { 'label': 'Portuguese - Portugal (pt-PT)', 'value': 'pt-PT' },
          { 'label': 'Romanian (ro)', 'value': 'ro' },
          { 'label': 'Romanian - Romania (ro-RO)', 'value': 'ro-RO' },
          { 'label': 'Russian (ru)', 'value': 'ru' },
          { 'label': 'Sinhala (si)', 'value': 'si' },
          { 'label': 'Sinhala - Sri Lanka (si-LK)', 'value': 'si-LK' },
          { 'label': 'Spanish (es)', 'value': 'es' },
          { 'label': 'Spanish - Latin America (es-419)', 'value': 'es-419' },
          { 'label': 'Spanish - Spain (es-ES)', 'value': 'es-ES' },
          { 'label': 'Swedish (sv)', 'value': 'sv' },
          { 'label': 'Tamil (ta)', 'value': 'ta' },
          { 'label': 'Tamil - India (ta-IN)', 'value': 'ta-IN' },
          { 'label': 'Tamil - Sri Lanka (ta-LK)', 'value': 'ta-LK' },
          { 'label': 'Tamil - Malaysia (ta-MY)', 'value': 'ta-MY' },
          { 'label': 'Tamil - Singapore (ta-SG)', 'value': 'ta-SG' },
          { 'label': 'Telugu (te)', 'value': 'te' },
          { 'label': 'Telugu - India (te-IN)', 'value': 'te-IN' },
          { 'label': 'Thai (th)', 'value': 'th' },
          { 'label': 'Turkish (tr)', 'value': 'tr' },
          { 'label': 'Ukrainian (uk)', 'value': 'uk' },
          { 'label': 'Vietnamese (vi)', 'value': 'vi' },
          { 'label': 'Vietnamese - Vietnam (vi-VN)', 'value': 'vi-VN' },
        ],
        'value': 'en-US',
      },
    ]
  visible_properties: ['project_id', 'language_code']
google_translate:
  id: google_translate
  logo: google-translate.png
  i18n_key: google_translate
  action: /google_translate
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Google Cloud Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Google Cloud Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
    ]
  visible_properties: ['project_id']
dyte:
  id: dyte
  logo: dyte.png
  i18n_key: dyte
  action: /dyte
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'organization_id': { 'type': 'string' },
        },
      'required': ['api_key', 'organization_id'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Organization ID',
        'type': 'text',
        'name': 'organization_id',
        'validation': 'required',
      },
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
    ]
  visible_properties: ['organization_id']

shopify:
  id: shopify
  logo: shopify.png
  i18n_key: shopify
  hook_type: account
  allow_multiple_hooks: false

leadsquared:
  id: leadsquared
  feature_flag: crm_integration
  logo: leadsquared.png
  i18n_key: leadsquared
  action: /leadsquared
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'access_key': { 'type': 'string' },
          'secret_key': { 'type': 'string' },
          'endpoint_url': { 'type': 'string' },
          'app_url': { 'type': 'string' },
          'enable_conversation_activity': { 'type': 'boolean' },
          'enable_transcript_activity': { 'type': 'boolean' },
          'conversation_activity_score': { 'type': 'string' },
          'transcript_activity_score': { 'type': 'string' },
          'conversation_activity_code': { 'type': 'integer' },
          'transcript_activity_code': { 'type': 'integer' },
        },
      'required': ['access_key', 'secret_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Access Key',
        'type': 'text',
        'name': 'access_key',
        'validation': 'required',
      },
      {
        'label': 'Secret Key',
        'type': 'text',
        'name': 'secret_key',
        'validation': 'required',
      },
      {
        'label': 'Push Conversation Activity',
        'type': 'checkbox',
        'name': 'enable_conversation_activity',
        'help': 'Enable this option to push an activity when a conversation is created',
      },
      {
        'label': 'Conversation Activity Score',
        'type': 'number',
        'name': 'conversation_activity_score',
        'help': 'Score to assign to the conversation created activity, default is 0',
      },
      {
        'label': 'Push Transcript Activity',
        'type': 'checkbox',
        'name': 'enable_transcript_activity',
        'help': 'Enable this option to push an activity when a transcript is created',
      },
      {
        'label': 'Transcript Activity Score',
        'type': 'number',
        'name': 'transcript_activity_score',
        'help': 'Score to assign to the conversation transcript activity, default is 0',
      },
    ]
  visible_properties:
    [
      'access_key',
      'endpoint_url',
      'enable_conversation_activity',
      'enable_transcript_activity',
      'conversation_activity_score',
      'transcript_activity_score',
    ]
