######  Attributes Supported by Integration Apps #######
# id: Internal Id for the integrations, used by the hooks
# logo: place the image in /public/dashboard/images/integrations and reference here
# i18n_key: the key under which translations for the integration is placed in en.yml
# action: if integration requires external redirect url
# hook_type: ( account / inbox )
# feature_flag: (string) feature flag to enable/disable the integration
# allow_multiple_hooks: whether multiple hooks can be created for the integration
# settings_json_schema: the json schema used to validate the settings hash (https://json-schema.org/)
# settings_form_schema: the formulate schema used in frontend to render settings form (https://vueformulate.com/)
########################################################
webhooks:
  id: webhook
  logo: webhooks.png
  i18n_key: webhooks
  action: /webhook
  hook_type: account
  allow_multiple_hooks: true
dashboard_apps:
  id: dashboard_apps
  logo: dashboard_apps.png
  i18n_key: dashboard_apps
  hook_type: account
  allow_multiple_hooks: true
openai:
  id: openai
  logo: openai.png
  i18n_key: openai
  action: /openai
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'label_suggestion': { 'type': 'boolean' },
        },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
      {
        'label': 'Show label suggestions',
        'type': 'checkbox',
        'name': 'label_suggestion',
        'validation': '',
      },
    ]
  visible_properties: ['api_key', 'label_suggestion']
linear:
  id: linear
  logo: linear.png
  i18n_key: linear
  action: https://linear.app/oauth/authorize
  hook_type: account
  allow_multiple_hooks: false
slack:
  id: slack
  logo: slack.png
  i18n_key: slack
  action: https://slack.com/oauth/v2/authorize?scope=commands,chat:write,channels:read,channels:manage,channels:join,groups:read,groups:write,im:write,mpim:write,users:read,users:read.email,chat:write.customize,channels:history,groups:history,mpim:history,im:history,files:read,files:write
  hook_type: account
  allow_multiple_hooks: false
dialogflow:
  id: dialogflow
  logo: dialogflow.png
  i18n_key: dialogflow
  action: /dialogflow
  hook_type: inbox
  allow_multiple_hooks: true
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
          'language_code': { 'type': 'string' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Dialogflow Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Dialogflow Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
      {
        'label': 'Dialogflow Language Code',
        'type': 'select',
        'name': 'language_code',
        'options': [
          { 'label': 'en-US', 'value': 'en-US' },
          { 'label': 'de', 'value': 'de' },
          { 'label': 'de-at', 'value': 'de-at' },
          { 'label': 'de-be', 'value': 'de-be' },
          { 'label': 'de-ch', 'value': 'de-ch' },
          { 'label': 'de-li', 'value': 'de-li' },
          { 'label': 'en-au', 'value': 'en-au' },
          { 'label': 'en-nz', 'value': 'en-nz' },
          { 'label': 'en-pg', 'value': 'en-pg' },
          { 'label': 'en-gb', 'value': 'en-gb' },
          { 'label': 'en-bw', 'value': 'en-bw' },
          { 'label': 'en-eg', 'value': 'en-eg' },
          { 'label': 'en-gh', 'value': 'en-gh' },
          { 'label': 'en-hk', 'value': 'en-hk' },
          { 'label': 'en-ie', 'value': 'en-ie' },
          { 'label': 'en-ke', 'value': 'en-ke' },
          { 'label': 'en-mt', 'value': 'en-mt' },
          { 'label': 'en-na', 'value': 'en-na' },
          { 'label': 'en-ng', 'value': 'en-ng' },
          { 'label': 'en-sg', 'value': 'en-sg' },
          { 'label': 'en-tz', 'value': 'en-tz' },
          { 'label': 'en-ug', 'value': 'en-ug' },
          { 'label': 'en-za', 'value': 'en-za' },
          { 'label': 'en-zm', 'value': 'en-zm' },
          { 'label': 'en-zw', 'value': 'en-zw' },
          { 'label': 'en-in', 'value': 'en-in' },
          { 'label': 'en-mu', 'value': 'en-mu' },
          { 'label': 'en', 'value': 'en' },
          { 'label': 'en-ae', 'value': 'en-ae' },
          { 'label': 'en-de', 'value': 'en-de' },
          { 'label': 'en-id', 'value': 'en-id' },
          { 'label': 'en-mm', 'value': 'en-mm' },
          { 'label': 'en-my', 'value': 'en-my' },
          { 'label': 'en-nl', 'value': 'en-nl' },
          { 'label': 'en-ph', 'value': 'en-ph' },
          { 'label': 'en-sa', 'value': 'en-sa' },
          { 'label': 'en-se', 'value': 'en-se' },
          { 'label': 'en-th', 'value': 'en-th' },
          { 'label': 'es-419', 'value': 'es-419' },
          { 'label': 'es-ar', 'value': 'es-ar' },
          { 'label': 'es-bo', 'value': 'es-bo' },
          { 'label': 'es-cl', 'value': 'es-cl' },
          { 'label': 'es-co', 'value': 'es-co' },
          { 'label': 'es-cr', 'value': 'es-cr' },
          { 'label': 'es-do', 'value': 'es-do' },
          { 'label': 'es-ec', 'value': 'es-ec' },
          { 'label': 'es-gt', 'value': 'es-gt' },
          { 'label': 'es-hn', 'value': 'es-hn' },
          { 'label': 'es-mx', 'value': 'es-mx' },
          { 'label': 'es-ni', 'value': 'es-ni' },
          { 'label': 'es-pa', 'value': 'es-pa' },
          { 'label': 'es-pe', 'value': 'es-pe' },
          { 'label': 'es-ph', 'value': 'es-ph' },
          { 'label': 'es-pr', 'value': 'es-pr' },
          { 'label': 'es-py', 'value': 'es-py' },
          { 'label': 'es-sv', 'value': 'es-sv' },
          { 'label': 'es-us', 'value': 'es-us' },
          { 'label': 'es-uy', 'value': 'es-uy' },
          { 'label': 'es-ve', 'value': 'es-ve' },
          { 'label': 'fil', 'value': 'fil' },
          { 'label': 'tl', 'value': 'tl' },
          { 'label': 'fil-ph', 'value': 'fil-ph' },
          { 'label': 'tl-ph', 'value': 'tl-ph' },
          { 'label': 'fr', 'value': 'fr' },
          { 'label': 'fr-be', 'value': 'fr-be' },
          { 'label': 'fr-cd', 'value': 'fr-cd' },
          { 'label': 'fr-ch', 'value': 'fr-ch' },
          { 'label': 'fr-ci', 'value': 'fr-ci' },
          { 'label': 'fr-cm', 'value': 'fr-cm' },
          { 'label': 'fr-dz', 'value': 'fr-dz' },
          { 'label': 'fr-es', 'value': 'fr-es' },
          { 'label': 'fr-gb', 'value': 'fr-gb' },
          { 'label': 'fr-gp', 'value': 'fr-gp' },
          { 'label': 'fr-ma', 'value': 'fr-ma' },
          { 'label': 'fr-mc', 'value': 'fr-mc' },
          { 'label': 'fr-mu', 'value': 'fr-mu' },
          { 'label': 'fr-re', 'value': 'fr-re' },
          { 'label': 'fr-sn', 'value': 'fr-sn' },
          { 'label': 'fr-tn', 'value': 'fr-tn' },
          { 'label': 'fr-us', 'value': 'fr-us' },
          { 'label': 'it', 'value': 'it' },
          { 'label': 'it-it', 'value': 'it-it' },
          { 'label': 'it-ch', 'value': 'it-ch' },
          { 'label': 'nl', 'value': 'nl' },
          { 'label': 'nl-be', 'value': 'nl-be' },
        ],
        'value': 'en-US',
      },
    ]
  visible_properties: ['project_id', 'language_code']
google_translate:
  id: google_translate
  logo: google-translate.png
  i18n_key: google_translate
  action: /google_translate
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Google Cloud Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Google Cloud Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
    ]
  visible_properties: ['project_id']
dyte:
  id: dyte
  logo: dyte.png
  i18n_key: dyte
  action: /dyte
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'organization_id': { 'type': 'string' },
        },
      'required': ['api_key', 'organization_id'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Organization ID',
        'type': 'text',
        'name': 'organization_id',
        'validation': 'required',
      },
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
    ]
  visible_properties: ['organization_id']

shopify:
  id: shopify
  logo: shopify.png
  i18n_key: shopify
  hook_type: account
  allow_multiple_hooks: false

leadsquared:
  id: leadsquared
  feature_flag: crm_integration
  logo: leadsquared.png
  i18n_key: leadsquared
  action: /leadsquared
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'access_key': { 'type': 'string' },
          'secret_key': { 'type': 'string' },
          'endpoint_url': { 'type': 'string' },
          'app_url': { 'type': 'string' },
          'enable_conversation_activity': { 'type': 'boolean' },
          'enable_transcript_activity': { 'type': 'boolean' },
          'conversation_activity_score': { 'type': 'string' },
          'transcript_activity_score': { 'type': 'string' },
          'conversation_activity_code': { 'type': 'integer' },
          'transcript_activity_code': { 'type': 'integer' },
        },
      'required': ['access_key', 'secret_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Access Key',
        'type': 'text',
        'name': 'access_key',
        'validation': 'required',
      },
      {
        'label': 'Secret Key',
        'type': 'text',
        'name': 'secret_key',
        'validation': 'required',
      },
      {
        'label': 'Push Conversation Activity',
        'type': 'checkbox',
        'name': 'enable_conversation_activity',
        'help': 'Enable this option to push an activity when a conversation is created',
      },
      {
        'label': 'Conversation Activity Score',
        'type': 'number',
        'name': 'conversation_activity_score',
        'help': 'Score to assign to the conversation created activity, default is 0',
      },
      {
        'label': 'Push Transcript Activity',
        'type': 'checkbox',
        'name': 'enable_transcript_activity',
        'help': 'Enable this option to push an activity when a transcript is created',
      },
      {
        'label': 'Transcript Activity Score',
        'type': 'number',
        'name': 'transcript_activity_score',
        'help': 'Score to assign to the conversation transcript activity, default is 0',
      },
    ]
  visible_properties:
    [
      'access_key',
      'endpoint_url',
      'enable_conversation_activity',
      'enable_transcript_activity',
      'conversation_activity_score',
      'transcript_activity_score',
    ]
