version: 2.1
orbs:
  node: circleci/node@6.1.0

defaults: &defaults
  working_directory: ~/build
  machine:
    image: ubuntu-2204:2024.05.1
  resource_class: large
  environment:
    RAILS_LOG_TO_STDOUT: false
    COVERAGE: true
    LOG_LEVEL: warn

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - node/install:
          node-version: '23.7'
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
          override-ci-command: pnpm i
      - run:
          name: Install System Dependencies and Ruby
          command: |
            sudo apt-get update -y && sudo apt-get install -y \
              gpg libssl-dev zlib1g-dev libyaml-dev libreadline-dev libpq-dev libxml2-dev libxslt1-dev \
              imagemagick libvips redis-server postgresql-14 postgresql-14-pgextwlist build-essential openjdk-11-jdk
            gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
            curl -sSL https://get.rvm.io | bash -s stable --ruby=3.3.3
            source ~/.rvm/scripts/rvm
            gem install bundler -v 2.5.16
            bundle install
      - persist_to_workspace:
          root: ~/build
          paths:
            - .
            - ~/.rvm
            - ~/.pnpm-store

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: Linting & Swagger
          command: |
            source ~/.rvm/scripts/rvm
            bundle exec rubocop
            pnpm eslint .
            bundle exec rake swagger:build

  security_audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: Security audit
          command: |
            source ~/.rvm/scripts/rvm
            bundle exec bundle audit update
            bundle exec bundle audit check --verbose

  frontend_tests:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: Run frontend tests
          command: |
            pnpm test

  backend_tests:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: Setup and start services
          command: |
            sudo service postgresql start
            sudo service redis-server start
      - run:
          name: Configure DB & Environment
          command: |
            source ~/.rvm/scripts/rvm
            cp .circleci/setup_chatwoot.sql /tmp/
            sudo -u postgres psql < .circleci/setup_chatwoot.sql
            bundle exec rails db:setup
      - run:
          name: Run backend tests
          command: |
            source ~/.rvm/scripts/rvm
            TEST_FILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TEST_FILES --format progress

workflows:
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - frontend_tests:
          requires:
            - setup
      - backend_tests:
          requires:
            - setup
      - security_audit:
          requires:
            - setup
